// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package us_state

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	typespb "northwind/proto/typespb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UsStateClient is the client API for UsState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsStateClient interface {
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UsStateByStateID(ctx context.Context, in *UsStateByStateIDRequest, opts ...grpc.CallOption) (*typespb.UsState, error)
}

type usStateClient struct {
	cc grpc.ClientConnInterface
}

func NewUsStateClient(cc grpc.ClientConnInterface) UsStateClient {
	return &usStateClient{cc}
}

func (c *usStateClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/us_state.UsState/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usStateClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/us_state.UsState/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usStateClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/us_state.UsState/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usStateClient) Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/us_state.UsState/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usStateClient) UsStateByStateID(ctx context.Context, in *UsStateByStateIDRequest, opts ...grpc.CallOption) (*typespb.UsState, error) {
	out := new(typespb.UsState)
	err := c.cc.Invoke(ctx, "/us_state.UsState/UsStateByStateID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsStateServer is the server API for UsState service.
// All implementations must embed UnimplementedUsStateServer
// for forward compatibility
type UsStateServer interface {
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	Insert(context.Context, *InsertRequest) (*emptypb.Empty, error)
	Update(context.Context, *UpdateRequest) (*emptypb.Empty, error)
	Upsert(context.Context, *UpsertRequest) (*emptypb.Empty, error)
	UsStateByStateID(context.Context, *UsStateByStateIDRequest) (*typespb.UsState, error)
	mustEmbedUnimplementedUsStateServer()
}

// UnimplementedUsStateServer must be embedded to have forward compatible implementations.
type UnimplementedUsStateServer struct {
}

func (UnimplementedUsStateServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUsStateServer) Insert(context.Context, *InsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedUsStateServer) Update(context.Context, *UpdateRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUsStateServer) Upsert(context.Context, *UpsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedUsStateServer) UsStateByStateID(context.Context, *UsStateByStateIDRequest) (*typespb.UsState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsStateByStateID not implemented")
}
func (UnimplementedUsStateServer) mustEmbedUnimplementedUsStateServer() {}

// UnsafeUsStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsStateServer will
// result in compilation errors.
type UnsafeUsStateServer interface {
	mustEmbedUnimplementedUsStateServer()
}

func RegisterUsStateServer(s grpc.ServiceRegistrar, srv UsStateServer) {
	s.RegisterService(&UsState_ServiceDesc, srv)
}

func _UsState_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsStateServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/us_state.UsState/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsStateServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsState_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsStateServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/us_state.UsState/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsStateServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsState_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsStateServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/us_state.UsState/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsStateServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsState_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsStateServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/us_state.UsState/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsStateServer).Upsert(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsState_UsStateByStateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsStateByStateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsStateServer).UsStateByStateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/us_state.UsState/UsStateByStateID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsStateServer).UsStateByStateID(ctx, req.(*UsStateByStateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsState_ServiceDesc is the grpc.ServiceDesc for UsState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "us_state.UsState",
	HandlerType: (*UsStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _UsState_Delete_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _UsState_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UsState_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _UsState_Upsert_Handler,
		},
		{
			MethodName: "UsStateByStateID",
			Handler:    _UsState_UsStateByStateID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "us_state.proto",
}
