// Code generated by xo-grpc (https://github.com/walterwanderley/xo-grpc).

package main

import (
	"database/sql"

	"go.uber.org/zap"
	"google.golang.org/grpc"

	pb_Category "northwind/api/category/v1"
	pb_Customer "northwind/api/customer/v1"
	pb_Employee "northwind/api/employee/v1"
	pb_Order "northwind/api/order/v1"
	pb_OrderDetail "northwind/api/order_detail/v1"
	pb_Product "northwind/api/product/v1"
	pb_Shipper "northwind/api/shipper/v1"
	pb_Supplier "northwind/api/supplier/v1"
	"northwind/internal/application"
	"northwind/internal/server"
)

func registerServer(logger *zap.Logger, db *sql.DB) server.RegisterServer {
	return func(grpcServer *grpc.Server) {
		pb_Category.RegisterCategoryServiceServer(grpcServer, application.NewCategoryService(logger, db))
		pb_Customer.RegisterCustomerServiceServer(grpcServer, application.NewCustomerService(logger, db))
		pb_Employee.RegisterEmployeeServiceServer(grpcServer, application.NewEmployeeService(logger, db))
		pb_Order.RegisterOrderServiceServer(grpcServer, application.NewOrderService(logger, db))
		pb_OrderDetail.RegisterOrderDetailServiceServer(grpcServer, application.NewOrderDetailService(logger, db))
		pb_Product.RegisterProductServiceServer(grpcServer, application.NewProductService(logger, db))
		pb_Shipper.RegisterShipperServiceServer(grpcServer, application.NewShipperService(logger, db))
		pb_Supplier.RegisterSupplierServiceServer(grpcServer, application.NewSupplierService(logger, db))

	}
}

func registerHandlers() []server.RegisterHandler {
	var handlers []server.RegisterHandler

	handlers = append(handlers, pb_Category.RegisterCategoryServiceHandler)
	handlers = append(handlers, pb_Customer.RegisterCustomerServiceHandler)
	handlers = append(handlers, pb_Employee.RegisterEmployeeServiceHandler)
	handlers = append(handlers, pb_Order.RegisterOrderServiceHandler)
	handlers = append(handlers, pb_OrderDetail.RegisterOrderDetailServiceHandler)
	handlers = append(handlers, pb_Product.RegisterProductServiceHandler)
	handlers = append(handlers, pb_Shipper.RegisterShipperServiceHandler)
	handlers = append(handlers, pb_Supplier.RegisterSupplierServiceHandler)

	return handlers
}
