// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package customer_demographic

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	typespb "northwind/proto/typespb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomerDemographicClient is the client API for CustomerDemographic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerDemographicClient interface {
	CustomerDemographicByCustomerTypeID(ctx context.Context, in *CustomerDemographicByCustomerTypeIDRequest, opts ...grpc.CallOption) (*typespb.CustomerDemographic, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type customerDemographicClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerDemographicClient(cc grpc.ClientConnInterface) CustomerDemographicClient {
	return &customerDemographicClient{cc}
}

func (c *customerDemographicClient) CustomerDemographicByCustomerTypeID(ctx context.Context, in *CustomerDemographicByCustomerTypeIDRequest, opts ...grpc.CallOption) (*typespb.CustomerDemographic, error) {
	out := new(typespb.CustomerDemographic)
	err := c.cc.Invoke(ctx, "/customer_demographic.CustomerDemographic/CustomerDemographicByCustomerTypeID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerDemographicClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_demographic.CustomerDemographic/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerDemographicClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_demographic.CustomerDemographic/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerDemographicClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_demographic.CustomerDemographic/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerDemographicClient) Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_demographic.CustomerDemographic/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerDemographicServer is the server API for CustomerDemographic service.
// All implementations must embed UnimplementedCustomerDemographicServer
// for forward compatibility
type CustomerDemographicServer interface {
	CustomerDemographicByCustomerTypeID(context.Context, *CustomerDemographicByCustomerTypeIDRequest) (*typespb.CustomerDemographic, error)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	Insert(context.Context, *InsertRequest) (*emptypb.Empty, error)
	Update(context.Context, *UpdateRequest) (*emptypb.Empty, error)
	Upsert(context.Context, *UpsertRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCustomerDemographicServer()
}

// UnimplementedCustomerDemographicServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerDemographicServer struct {
}

func (UnimplementedCustomerDemographicServer) CustomerDemographicByCustomerTypeID(context.Context, *CustomerDemographicByCustomerTypeIDRequest) (*typespb.CustomerDemographic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerDemographicByCustomerTypeID not implemented")
}
func (UnimplementedCustomerDemographicServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCustomerDemographicServer) Insert(context.Context, *InsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedCustomerDemographicServer) Update(context.Context, *UpdateRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCustomerDemographicServer) Upsert(context.Context, *UpsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedCustomerDemographicServer) mustEmbedUnimplementedCustomerDemographicServer() {}

// UnsafeCustomerDemographicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerDemographicServer will
// result in compilation errors.
type UnsafeCustomerDemographicServer interface {
	mustEmbedUnimplementedCustomerDemographicServer()
}

func RegisterCustomerDemographicServer(s grpc.ServiceRegistrar, srv CustomerDemographicServer) {
	s.RegisterService(&CustomerDemographic_ServiceDesc, srv)
}

func _CustomerDemographic_CustomerDemographicByCustomerTypeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDemographicByCustomerTypeIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerDemographicServer).CustomerDemographicByCustomerTypeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_demographic.CustomerDemographic/CustomerDemographicByCustomerTypeID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerDemographicServer).CustomerDemographicByCustomerTypeID(ctx, req.(*CustomerDemographicByCustomerTypeIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerDemographic_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerDemographicServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_demographic.CustomerDemographic/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerDemographicServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerDemographic_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerDemographicServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_demographic.CustomerDemographic/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerDemographicServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerDemographic_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerDemographicServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_demographic.CustomerDemographic/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerDemographicServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerDemographic_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerDemographicServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_demographic.CustomerDemographic/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerDemographicServer).Upsert(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerDemographic_ServiceDesc is the grpc.ServiceDesc for CustomerDemographic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerDemographic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer_demographic.CustomerDemographic",
	HandlerType: (*CustomerDemographicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomerDemographicByCustomerTypeID",
			Handler:    _CustomerDemographic_CustomerDemographicByCustomerTypeID_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomerDemographic_Delete_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _CustomerDemographic_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomerDemographic_Update_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _CustomerDemographic_Upsert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer_demographic.proto",
}
