// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package customer_customer_demo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	typespb "northwind/proto/typespb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomerCustomerDemoClient is the client API for CustomerCustomerDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerCustomerDemoClient interface {
	Customer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*typespb.Customer, error)
	CustomerCustomerDemoByCustomerIDCustomerTypeID(ctx context.Context, in *CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest, opts ...grpc.CallOption) (*typespb.CustomerCustomerDemo, error)
	CustomerDemographic(ctx context.Context, in *CustomerDemographicRequest, opts ...grpc.CallOption) (*typespb.CustomerDemographic, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type customerCustomerDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerCustomerDemoClient(cc grpc.ClientConnInterface) CustomerCustomerDemoClient {
	return &customerCustomerDemoClient{cc}
}

func (c *customerCustomerDemoClient) Customer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*typespb.Customer, error) {
	out := new(typespb.Customer)
	err := c.cc.Invoke(ctx, "/customer_customer_demo.CustomerCustomerDemo/Customer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerCustomerDemoClient) CustomerCustomerDemoByCustomerIDCustomerTypeID(ctx context.Context, in *CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest, opts ...grpc.CallOption) (*typespb.CustomerCustomerDemo, error) {
	out := new(typespb.CustomerCustomerDemo)
	err := c.cc.Invoke(ctx, "/customer_customer_demo.CustomerCustomerDemo/CustomerCustomerDemoByCustomerIDCustomerTypeID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerCustomerDemoClient) CustomerDemographic(ctx context.Context, in *CustomerDemographicRequest, opts ...grpc.CallOption) (*typespb.CustomerDemographic, error) {
	out := new(typespb.CustomerDemographic)
	err := c.cc.Invoke(ctx, "/customer_customer_demo.CustomerCustomerDemo/CustomerDemographic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerCustomerDemoClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_customer_demo.CustomerCustomerDemo/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerCustomerDemoClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/customer_customer_demo.CustomerCustomerDemo/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerCustomerDemoServer is the server API for CustomerCustomerDemo service.
// All implementations must embed UnimplementedCustomerCustomerDemoServer
// for forward compatibility
type CustomerCustomerDemoServer interface {
	Customer(context.Context, *CustomerRequest) (*typespb.Customer, error)
	CustomerCustomerDemoByCustomerIDCustomerTypeID(context.Context, *CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest) (*typespb.CustomerCustomerDemo, error)
	CustomerDemographic(context.Context, *CustomerDemographicRequest) (*typespb.CustomerDemographic, error)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	Insert(context.Context, *InsertRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCustomerCustomerDemoServer()
}

// UnimplementedCustomerCustomerDemoServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerCustomerDemoServer struct {
}

func (UnimplementedCustomerCustomerDemoServer) Customer(context.Context, *CustomerRequest) (*typespb.Customer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Customer not implemented")
}
func (UnimplementedCustomerCustomerDemoServer) CustomerCustomerDemoByCustomerIDCustomerTypeID(context.Context, *CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest) (*typespb.CustomerCustomerDemo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerCustomerDemoByCustomerIDCustomerTypeID not implemented")
}
func (UnimplementedCustomerCustomerDemoServer) CustomerDemographic(context.Context, *CustomerDemographicRequest) (*typespb.CustomerDemographic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomerDemographic not implemented")
}
func (UnimplementedCustomerCustomerDemoServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCustomerCustomerDemoServer) Insert(context.Context, *InsertRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedCustomerCustomerDemoServer) mustEmbedUnimplementedCustomerCustomerDemoServer() {}

// UnsafeCustomerCustomerDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerCustomerDemoServer will
// result in compilation errors.
type UnsafeCustomerCustomerDemoServer interface {
	mustEmbedUnimplementedCustomerCustomerDemoServer()
}

func RegisterCustomerCustomerDemoServer(s grpc.ServiceRegistrar, srv CustomerCustomerDemoServer) {
	s.RegisterService(&CustomerCustomerDemo_ServiceDesc, srv)
}

func _CustomerCustomerDemo_Customer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerCustomerDemoServer).Customer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_customer_demo.CustomerCustomerDemo/Customer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerCustomerDemoServer).Customer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerCustomerDemo_CustomerCustomerDemoByCustomerIDCustomerTypeID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerCustomerDemoServer).CustomerCustomerDemoByCustomerIDCustomerTypeID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_customer_demo.CustomerCustomerDemo/CustomerCustomerDemoByCustomerIDCustomerTypeID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerCustomerDemoServer).CustomerCustomerDemoByCustomerIDCustomerTypeID(ctx, req.(*CustomerCustomerDemoByCustomerIDCustomerTypeIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerCustomerDemo_CustomerDemographic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerDemographicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerCustomerDemoServer).CustomerDemographic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_customer_demo.CustomerCustomerDemo/CustomerDemographic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerCustomerDemoServer).CustomerDemographic(ctx, req.(*CustomerDemographicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerCustomerDemo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerCustomerDemoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_customer_demo.CustomerCustomerDemo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerCustomerDemoServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerCustomerDemo_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerCustomerDemoServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer_customer_demo.CustomerCustomerDemo/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerCustomerDemoServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerCustomerDemo_ServiceDesc is the grpc.ServiceDesc for CustomerCustomerDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerCustomerDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "customer_customer_demo.CustomerCustomerDemo",
	HandlerType: (*CustomerCustomerDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Customer",
			Handler:    _CustomerCustomerDemo_Customer_Handler,
		},
		{
			MethodName: "CustomerCustomerDemoByCustomerIDCustomerTypeID",
			Handler:    _CustomerCustomerDemo_CustomerCustomerDemoByCustomerIDCustomerTypeID_Handler,
		},
		{
			MethodName: "CustomerDemographic",
			Handler:    _CustomerCustomerDemo_CustomerDemographic_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomerCustomerDemo_Delete_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _CustomerCustomerDemo_Insert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer_customer_demo.proto",
}
